# (DON'T CHANGE) remote base path and project repo folder name
base_path = "/home/smr"
repo_name = "summerset"

# (SET PROPERLY) for each group, its DNS domain names;
#                please leave username unchanged as smr
[reg]
host0 = "smr@<domain.name>"
host1 = "smr@<domain.name>"
host2 = "smr@<domain.name>"
host3 = "smr@<domain.name>"
host4 = "smr@<domain.name>"

[wan]
host0 = "smr@<domain.name>"
host1 = "smr@<domain.name>"
host2 = "smr@<domain.name>"
host3 = "smr@<domain.name>"
host4 = "smr@<domain.name>"
